const fontsList = [
  'American Typewriter, serif',
  'Andale Mono, monospace',
  'Apple Chancery, cursive',
  'Arial Narrow, sans-serif',
  'Arial, sans-serif',
  'Avantgarde, TeX Gyre Adventor, URW Gothic L, sans-serif',
  'Blippo, fantasy',
  'Bookman, URW Bookman L, serif',
  'Bradley Hand, cursive',
  'Brush Script MT, Brush Script Std, cursive',
  'Chalkduster, fantasy',
  'Comic Sans MS, Comic Sans, cursive',
  'Courier New, monospace',
  'Courier, monospace',
  'DejaVu Sans Mono, monospace',
  'Didot, serif',
  'FreeMono, monospace',
  'Georgia, serif',
  'Gill Sans, sans-serif',
  'Helvetica, sans-serif',
  'Impact, fantasy',
  'Jazz LET, fantasy',
  'Luminari, fantasy',
  'Marker Felt, fantasy',
  'New Century Schoolbook, TeX Gyre Schola, serif',
  'Noto Sans, sans-serif',
  'OCR A Std, monospace',
  'Optima, sans-serif',
  'Palatino, URW Palladio L, serif',
  'Poppins, sans-serif',
  'Snell Roundhand, cursive',
  'Stencil Std, fantasy',
  'Times, Times New Roman, serif',
  'Trattatello, fantasy',
  'Trebuchet MS, sans-serif',
  'URW Chancery L, cursive',
  'Verdana, sans-serif',
  'cursive',
  'fantasy',
  'monospace',
  'sans-serif',
  'serif',
];

export default fontsList;
